ENV['RCT_NEW_ARCH_ENABLED'] = '1'
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require Pod::Executable.execute_command('node', ['-p', 'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]).strip

MIN_IOS_OVERRIDE = '15.5'
if Gem::Version.new(MIN_IOS_OVERRIDE) > Gem::Version.new(min_ios_version_supported)
  min_ios_version_supported = MIN_IOS_OVERRIDE
end

platform :ios, min_ios_version_supported
prepare_react_native_project!

production = ENV["PRODUCTION"] == "1"
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReaderApp' do
  use_expo_modules!
  pod 'SpotlightIndexer', :path => './SpotlightIndexer'

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  $config = use_native_modules!
  use_react_native!(
    :path => $config[:reactNativePath],
    :production => production,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

post_install do |installer|
  react_native_post_install(
    installer,
    $config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
  installer.pods_project.build_configurations.each do |curr_config|
    curr_config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
